import { describe, it, expect, vi } from 'vitest'
import {
  CitationCollector,
  extractCitationsFromToolResult,
  formatCitationFooter,
} from '../engine'
import type { CitationConfig } from '../../types/platform'

// Citations are the OS's primary trust gate ("cite or shut up"). Without
// these tests the citation engine ships unlabelled — silent regressions
// are exactly the failure mode the rule was written to catch.

describe('extractCitationsFromToolResult', () => {
  it('returns no citations for non-object input', () => {
    expect(
      extractCitationsFromToolResult('research_account', { foo: 'bar' }, null),
    ).toEqual([{ claim_text: 'research_account', source_type: 'research_account', source_id: undefined, source_url: undefined, confidence: undefined }])
  })

  it('uses citation_config to pick the id field and url template', () => {
    const config: CitationConfig = {
      source_type: 'company',
      id_field: 'crm_id',
      url_template: 'https://crm.example.com/co/{crm_id}',
    }
    const result = { name: 'Acme', crm_id: '0001-abc', confidence: 0.9 }

    const citations = extractCitationsFromToolResult('research_account', result, config)

    expect(citations).toHaveLength(1)
    expect(citations[0]).toEqual({
      claim_text: 'Acme',
      source_type: 'company',
      source_id: '0001-abc',
      source_url: 'https://crm.example.com/co/0001-abc',
      confidence: 0.9,
    })
  })

  it('falls back to title or subject when no name is present', () => {
    const result = { title: 'Q3 Renewal', id: 'deal-7' }
    const [c] = extractCitationsFromToolResult('get_deal_detail', result, null)
    expect(c.claim_text).toBe('Q3 Renewal')
    expect(c.source_id).toBe('deal-7')
  })

  it('handles array results by emitting one citation per row', () => {
    const result = [
      { name: 'Acme', id: 'a' },
      { name: 'Beta', id: 'b' },
    ] as unknown as Record<string, unknown>
    const citations = extractCitationsFromToolResult('priority_queue', result, null)
    expect(citations.map((c) => c.claim_text)).toEqual(['Acme', 'Beta'])
  })

  it('does not invent a confidence when the row does not provide one', () => {
    const result = { name: 'Acme', id: 'a' }
    const [c] = extractCitationsFromToolResult('research_account', result, null)
    expect(c.confidence).toBeUndefined()
  })

  it('omits source_url when neither template nor explicit url is given', () => {
    const result = { name: 'Acme', id: 'a' }
    const [c] = extractCitationsFromToolResult('research_account', result, null)
    expect(c.source_url).toBeUndefined()
  })
})

describe('CitationCollector', () => {
  it('starts empty and accepts addCitation', () => {
    const c = new CitationCollector('tenant-1', 'interaction-1')
    expect(c.getCitations()).toEqual([])
    c.addCitation({ claim_text: 'Acme', source_type: 'company', source_id: '1' })
    expect(c.getCitations()).toHaveLength(1)
  })

  it('formatInline groups by source_type and pluralises counts', () => {
    const c = new CitationCollector('tenant-1', 'interaction-1')
    c.addCitation({ claim_text: 'Acme', source_type: 'company', source_id: '1' })
    c.addCitation({ claim_text: 'Beta', source_type: 'company', source_id: '2' })
    c.addCitation({ claim_text: 'Q3 Renewal', source_type: 'opportunity', source_id: 'd1' })

    const inline = c.formatInline()
    expect(inline).toContain('Company (2 records)')
    expect(inline).toContain('Opportunity')
  })

  it('formatInline returns empty string when nothing has been added', () => {
    const c = new CitationCollector('tenant-1', 'interaction-1')
    expect(c.formatInline()).toBe('')
  })

  it('formatFooter falls back to a clean footer when citations are empty', () => {
    const c = new CitationCollector('tenant-1', 'interaction-1')
    const footer = c.formatFooter()
    expect(footer).toContain('Generated by Revenue AI OS')
    expect(footer).toContain('Interaction ID: interaction-1')
  })

  it('flush is a no-op when there are no citations', async () => {
    const c = new CitationCollector('tenant-1', 'interaction-1')
    const fakeSupabase = { from: vi.fn() } as unknown as Parameters<typeof c.flush>[0]
    await expect(c.flush(fakeSupabase)).resolves.toBeUndefined()
    expect(fakeSupabase.from).not.toHaveBeenCalled()
  })

  it('flush inserts one row per citation, then clears the buffer', async () => {
    const insert = vi.fn().mockResolvedValue({ error: null })
    const fakeSupabase = { from: vi.fn().mockReturnValue({ insert }) } as unknown as Parameters<typeof CitationCollector.prototype.flush>[0]

    const c = new CitationCollector('tenant-1', 'interaction-1')
    c.addCitation({ claim_text: 'Acme', source_type: 'company', source_id: '1' })
    c.addCitation({ claim_text: 'Beta', source_type: 'company', source_id: '2' })

    await c.flush(fakeSupabase)

    expect(insert).toHaveBeenCalledTimes(1)
    const rows = insert.mock.calls[0][0]
    expect(rows).toHaveLength(2)
    expect(rows[0]).toMatchObject({
      tenant_id: 'tenant-1',
      interaction_id: 'interaction-1',
      claim_text: 'Acme',
      source_type: 'company',
    })
    expect(c.getCitations()).toEqual([])
  })

  it('flush surfaces a clean error message on Supabase failure', async () => {
    const insert = vi.fn().mockResolvedValue({ error: { message: 'permission denied' } })
    const fakeSupabase = { from: vi.fn().mockReturnValue({ insert }) } as unknown as Parameters<typeof CitationCollector.prototype.flush>[0]

    const c = new CitationCollector('tenant-1', 'interaction-1')
    c.addCitation({ claim_text: 'Acme', source_type: 'company' })

    await expect(c.flush(fakeSupabase)).rejects.toThrow('Citation flush failed: permission denied')
  })

  it('addFromToolResult routes through extractCitationsFromToolResult', () => {
    const c = new CitationCollector('tenant-1', 'interaction-1')
    c.addFromToolResult(
      'research_account',
      { name: 'Acme', id: 'a' } as unknown as Record<string, unknown>,
      null,
    )
    expect(c.getCitations()).toHaveLength(1)
    expect(c.getCitations()[0].claim_text).toBe('Acme')
  })

  it('setInteractionId updates the in-flight collector', async () => {
    const insert = vi.fn().mockResolvedValue({ error: null })
    const fakeSupabase = { from: vi.fn().mockReturnValue({ insert }) } as unknown as Parameters<typeof CitationCollector.prototype.flush>[0]

    const c = new CitationCollector('tenant-1')
    c.addCitation({ claim_text: 'Acme', source_type: 'company' })
    c.setInteractionId('late-binding-interaction')

    await c.flush(fakeSupabase)

    const rows = insert.mock.calls[0][0]
    expect(rows[0].interaction_id).toBe('late-binding-interaction')
  })
})

describe('formatCitationFooter', () => {
  it('returns a placeholder line when there are no citations', () => {
    const footer = formatCitationFooter([], 'i-1')
    expect(footer).toContain('Generated by Revenue AI OS')
    expect(footer).toContain('Interaction ID: i-1')
  })

  it('includes a Sources line listing distinct source types', () => {
    const footer = formatCitationFooter(
      [
        { claim_text: 'Acme', source_type: 'company', source_id: '1' },
        { claim_text: 'Q3 Renewal', source_type: 'opportunity', source_id: 'd1' },
        { claim_text: 'Acme', source_type: 'company', source_id: '1' },
      ],
      'i-1',
    )
    expect(footer).toContain('Sources:')
    expect(footer).toContain('Company')
    expect(footer).toContain('Opportunity')
  })

  it('prefers source_url over claim text when present', () => {
    const footer = formatCitationFooter(
      [
        {
          claim_text: 'Acme',
          source_type: 'company',
          source_id: '1',
          source_url: 'https://crm.example.com/co/1',
        },
      ],
      'i-1',
    )
    expect(footer).toContain('https://crm.example.com/co/1')
  })
})
