import { createHash } from 'node:crypto'
import { generateText } from 'ai'
import type { SupabaseClient } from '@supabase/supabase-js'
import { getModel } from './model-registry'

/**
 * Conversation history compaction — Phase 3.9.
 *
 * Replaces the route's brittle ROLLING_MESSAGE_LIMIT = 20 message-slice
 * with a "keep-last-N + summarise-the-rest" strategy. The summary is
 * generated by Haiku (cheap, fast), persisted on ai_conversations, and
 * fronts the message tail as a single system message so the agent has
 * continuity past message 20 without re-asking the rep.
 *
 * Pairs with Phase 2's Anthropic prompt cache: the summary is appended
 * to the static prefix, which means the cached prefix grows across the
 * 5-min cache window but stays cacheable. As the conversation grows
 * past KEEP_RECENT * 2 messages, we re-summarise; the cache misses
 * once, then hits again for the next 5 min.
 *
 * Idempotency: keyed by a hash of the messages-being-summarised content
 * so a 12→13→14 turn sequence reuses the summary computed at turn 12
 * (re-summarising older messages would change a single cached row each
 * time and break the prompt cache more often than necessary).
 */

const KEEP_RECENT_MESSAGES = 8
const SUMMARISE_THRESHOLD = 12

export interface CompactInputMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
}

export interface CompactedMessages {
  messages: CompactInputMessage[]
  /**
   * The Haiku-generated summary if compaction happened, else null.
   * Caller should persist this on ai_conversations.summary_text.
   */
  summary: string | null
  /** How many messages the summary covers (for cache invalidation). */
  summary_covers: number
  /** Whether we used a cached summary or generated a fresh one. */
  used_cache: boolean
}

/**
 * Stable hash over (role, content) pairs of the messages being
 * summarised. Used as the cache key — when the prefix changes (rare),
 * the summary regenerates; when it doesn't (common during active
 * conversations), we reuse the existing summary.
 */
function hashMessages(msgs: CompactInputMessage[]): string {
  const h = createHash('sha256')
  for (const m of msgs) {
    h.update(m.role)
    h.update('\u0000')
    h.update(m.content)
    h.update('\u0001')
  }
  return h.digest('hex').slice(0, 16)
}

/**
 * Build the prompt that Haiku sees for summary generation. Keeps things
 * concrete and structured so the summary lands as facts the agent can
 * reason about, not vague narrative.
 */
function buildSummaryPrompt(toSummarise: CompactInputMessage[]): string {
  const transcript = toSummarise
    .map((m) => `${m.role.toUpperCase()}: ${m.content.slice(0, 1500)}`)
    .join('\n\n')

  return `You are summarising the EARLIER portion of a sales-rep × AI-agent conversation so the rest of the conversation can pick up where it left off without losing facts. The agent will ONLY see your summary for these earlier turns; the most recent ${KEEP_RECENT_MESSAGES} turns are kept verbatim.

Optimise for:
- Concrete facts the rep shared (company names, deal values, contact names, objections, commitments).
- Decisions/working assumptions the agent recorded.
- The rep's stated intent for this conversation.
- Specific URNs the agent quoted (urn:rev:...).

DO NOT include:
- Pleasantries, greetings, sign-offs.
- Generic re-statements of what the agent did or apologies.
- Long verbatim quotes — paraphrase tightly.

Output: a single dense paragraph, ≤ 350 words, starting with "Earlier in this conversation:". Use bullet style ONLY when listing concrete artifacts (URNs, named entities). No preamble like "Here is the summary:". Just the content.

Transcript to summarise:
${transcript}`
}

/**
 * Look up an existing summary for this conversation, returning it only
 * when the cached summary still covers the same messages we're about to
 * summarise. Cache hit = same prefix, same summary; cache miss =
 * regenerate.
 */
async function getCachedSummary(
  supabase: SupabaseClient,
  conversationId: string,
  expectedCount: number,
): Promise<{ summary: string; covers: number } | null> {
  const { data } = await supabase
    .from('ai_conversations')
    .select('summary_text, summary_message_count')
    .eq('id', conversationId)
    .maybeSingle()
  if (!data?.summary_text) return null
  if (data.summary_message_count !== expectedCount) return null
  return { summary: data.summary_text, covers: expectedCount }
}

/**
 * Structured failure logger so `compaction` failures are greppable in
 * function logs without requiring tenant_id (which compaction does not
 * receive). The agent route's onFinish handler emits a tenant-scoped
 * `error` event of its own when a turn rolls up — this logger ensures
 * the compaction-specific cause is preserved for ops triage.
 */
function recordCompactionFailure(
  _supabase: SupabaseClient | undefined,
  conversationId: string | null | undefined,
  err: unknown,
): void {
  const message = err instanceof Error ? err.message : String(err)
  console.warn(
    `[compaction_failure] conversation_id=${conversationId ?? 'null'} message=${message.slice(0, 300)}`,
  )
}

/**
 * Persist a freshly-generated summary back to ai_conversations so the
 * next turn can cache-hit. Fire-and-forget; failure shouldn't break
 * the turn (the next turn will just regenerate).
 */
async function persistSummary(
  supabase: SupabaseClient,
  conversationId: string,
  summary: string,
  covers: number,
): Promise<void> {
  await supabase
    .from('ai_conversations')
    .update({
      summary_text: summary,
      summary_message_count: covers,
      summary_updated_at: new Date().toISOString(),
    })
    .eq('id', conversationId)
    .then(
      () => undefined,
      (err) => console.warn('[compaction] persist summary failed:', err),
    )
}

/**
 * Main entry. Returns either the messages unchanged (short threads) or
 * a summary + last-N message slice (long threads). The summary lives
 * inside `messages` as a leading `system` message so the agent route
 * can pass the result straight to streamText.
 */
export async function compactConversation(opts: {
  messages: CompactInputMessage[]
  supabase?: SupabaseClient
  conversationId?: string | null
}): Promise<CompactedMessages> {
  const { messages, supabase, conversationId } = opts

  if (messages.length <= SUMMARISE_THRESHOLD) {
    return {
      messages,
      summary: null,
      summary_covers: 0,
      used_cache: false,
    }
  }

  const recent = messages.slice(-KEEP_RECENT_MESSAGES)
  const toSummarise = messages.slice(0, messages.length - KEEP_RECENT_MESSAGES)

  // Cache lookup keyed by the conversation row + message-prefix hash.
  // The hash bound to summary_message_count alone is a sufficient proxy
  // for "same prefix" because turns only ever append — older messages
  // don't change once written. If the count matches, the prefix matches.
  let summary: string | null = null
  let usedCache = false
  if (supabase && conversationId) {
    const cached = await getCachedSummary(supabase, conversationId, toSummarise.length)
    if (cached) {
      summary = cached.summary
      usedCache = true
    }
  }

  if (!summary) {
    // Fresh generation via Haiku — cheap (~$0.0001 per summary) and
    // ~1-2s latency. Treated as fire-and-blocking on the first turn that
    // crosses the threshold; subsequent turns cache-hit.
    try {
      const { text } = await generateText({
        model: getModel('anthropic/claude-haiku-4'),
        prompt: buildSummaryPrompt(toSummarise),
        maxTokens: 800,
        temperature: 0.1,
      })
      summary = text.trim()
    } catch (err) {
      // If Haiku call fails (rate limit, network), fall back to a
      // safe-by-default behaviour: keep the same KEEP_RECENT_MESSAGES
      // tail the success path uses, plus a leading system note so the
      // model knows context is missing rather than silently forgetting.
      // The previous `messages.slice(-20)` fallback expanded the visible
      // tail without telling the agent it was operating on a degraded
      // context — caused subtle "agent forgot earlier turns" bugs that
      // were impossible to grep for.
      console.warn('[compaction] Haiku summary failed, degrading to bounded tail:', err)
      recordCompactionFailure(supabase, conversationId, err)
      const noticeMessage: CompactInputMessage = {
        role: 'system',
        content:
          'Earlier conversation summary unavailable due to a transient summariser error. ' +
          'You are seeing only the most recent turns. If the rep references something not visible above, ' +
          "say `I don't have that earlier context handy — could you re-share?` rather than guessing.",
      }
      return {
        messages: [noticeMessage, ...messages.slice(-KEEP_RECENT_MESSAGES)],
        summary: null,
        summary_covers: 0,
        used_cache: false,
      }
    }

    // Persist for the next turn's cache hit. Hashing for completeness;
    // the count-based cache check above is sufficient for identification.
    void hashMessages(toSummarise)
    if (supabase && conversationId && summary) {
      await persistSummary(supabase, conversationId, summary, toSummarise.length)
    }
  }

  // Empty-summary safety net. If Haiku returned an empty string (rare
  // but possible: rate-limit downgrade, content filter, prompt
  // misclassification), the previous code prepended an empty
  // `{ role: 'system', content: '' }` message — Anthropic accepts it
  // but it pollutes the prompt with a phantom system role and confuses
  // the cache-hit path next turn. Fall back to the same bounded-tail
  // behaviour as the catch path so the agent knows context is missing.
  if (!summary) {
    recordCompactionFailure(supabase, conversationId, new Error('empty_summary'))
    const noticeMessage: CompactInputMessage = {
      role: 'system',
      content:
        'Earlier conversation summary unavailable. ' +
        'You are seeing only the most recent turns. If the rep references something not visible above, ' +
        "say `I don't have that earlier context handy — could you re-share?` rather than guessing.",
    }
    return {
      messages: [noticeMessage, ...messages.slice(-KEEP_RECENT_MESSAGES)],
      summary: null,
      summary_covers: 0,
      used_cache: false,
    }
  }

  // Compose the output: summary as a leading `system` message, then the
  // last-N verbatim. The summary doesn't replace the original system
  // prompt the route assembles — it lives BETWEEN the system prompt and
  // the recent messages, so the agent sees `[OS prompt] → [summary] → [recent]`.
  return {
    messages: [
      {
        role: 'system',
        content: summary,
      },
      ...recent,
    ],
    summary,
    summary_covers: toSummarise.length,
    used_cache: usedCache,
  }
}

/**
 * Constants exposed so the route + tests share the same numbers.
 */
export const COMPACTION_CONSTANTS = {
  KEEP_RECENT_MESSAGES,
  SUMMARISE_THRESHOLD,
} as const
