import type { SupabaseClient } from '@supabase/supabase-js'
import type { CitationConfig } from '../types/platform'

export type { CitationConfig }

export interface PendingCitation {
  claim_text: string
  source_type: string
  source_id?: string
  source_url?: string
  confidence?: number
}

/**
 * Extracts citations from a tool result using the tool's citation config.
 * Handles both single objects and arrays of results.
 */
export function extractCitationsFromToolResult(
  toolSlug: string,
  result: Record<string, unknown>,
  citationConfig: CitationConfig | null
): PendingCitation[] {
  const items = Array.isArray(result) ? result : [result]
  const citations: PendingCitation[] = []

  for (const item of items) {
    if (item == null || typeof item !== 'object') continue
    const record = item as Record<string, unknown>

    const sourceId = citationConfig?.id_field
      ? String(record[citationConfig.id_field] ?? '')
      : String(record['id'] ?? '')

    let sourceUrl: string | undefined
    if (typeof record['source_url'] === 'string') {
      sourceUrl = record['source_url']
    } else if (citationConfig?.url_template) {
      sourceUrl = citationConfig.url_template.replace(
        /\{(\w+)\}/g,
        (_, field) => String(record[field] ?? '')
      )
    }

    const claimText = String(
      record['name'] ?? record['title'] ?? record['subject'] ?? toolSlug
    )

    citations.push({
      claim_text: claimText,
      source_type: citationConfig?.source_type ?? toolSlug,
      source_id: sourceId || undefined,
      source_url: sourceUrl,
      confidence:
        typeof record['confidence'] === 'number'
          ? record['confidence']
          : undefined,
    })
  }

  return citations
}

/**
 * Standard footer for CRM notes and exported content.
 */
export function formatCitationFooter(
  citations: PendingCitation[],
  interactionId: string
): string {
  if (citations.length === 0) {
    return `— Generated by Revenue AI OS\nGenerated: ${utcTimestamp()} · Interaction ID: ${interactionId}`
  }

  const labels = citations.map((c) => {
    const label = c.source_type.charAt(0).toUpperCase() + c.source_type.slice(1)
    if (c.source_url) return `${label} (${c.source_url})`
    return c.claim_text !== c.source_type ? `${label} ${c.claim_text}` : label
  })

  const uniqueLabels = [...new Set(labels)]

  return [
    '— Generated by Revenue AI OS',
    `Sources: ${uniqueLabels.join(' · ')}`,
    `Generated: ${utcTimestamp()} · Interaction ID: ${interactionId}`,
  ].join('\n')
}

/**
 * Collects citations during an agent interaction and writes them
 * to `agent_citations` at the end via `flush()`.
 */
export class CitationCollector {
  private citations: PendingCitation[] = []
  private tenantId: string
  private interactionId: string | null

  constructor(tenantId: string, interactionId?: string) {
    this.tenantId = tenantId
    this.interactionId = interactionId ?? null
  }

  addCitation(citation: PendingCitation): void {
    this.citations.push(citation)
  }

  addFromToolResult(
    toolSlug: string,
    result: Record<string, unknown>,
    citationConfig: CitationConfig | null
  ): void {
    const extracted = extractCitationsFromToolResult(
      toolSlug,
      result,
      citationConfig
    )
    this.citations.push(...extracted)
  }

  async flush(supabase: SupabaseClient): Promise<void> {
    if (this.citations.length === 0) return

    const rows = this.citations.map((c) => ({
      tenant_id: this.tenantId,
      interaction_id: this.interactionId,
      claim_text: c.claim_text,
      source_type: c.source_type,
      source_id: c.source_id ?? null,
      source_url: c.source_url ?? null,
      confidence: c.confidence ?? null,
    }))

    const { error } = await supabase.from('agent_citations').insert(rows)
    if (error) throw new Error(`Citation flush failed: ${error.message}`)

    this.citations = []
  }

  formatInline(): string {
    if (this.citations.length === 0) return ''

    const grouped = new Map<string, number>()
    for (const c of this.citations) {
      grouped.set(c.source_type, (grouped.get(c.source_type) ?? 0) + 1)
    }

    const parts: string[] = []
    for (const [type, count] of grouped) {
      const label = type.charAt(0).toUpperCase() + type.slice(1)
      parts.push(count === 1 ? label : `${label} (${count} records)`)
    }

    return `---\nSources: ${parts.join(' · ')}`
  }

  formatFooter(): string {
    return formatCitationFooter(
      this.citations,
      this.interactionId ?? 'unknown'
    )
  }

  getCitations(): PendingCitation[] {
    return [...this.citations]
  }

  setInteractionId(id: string): void {
    this.interactionId = id
  }
}

function utcTimestamp(): string {
  const now = new Date()
  const y = now.getUTCFullYear()
  const mo = String(now.getUTCMonth() + 1).padStart(2, '0')
  const d = String(now.getUTCDate()).padStart(2, '0')
  const h = String(now.getUTCHours()).padStart(2, '0')
  const mi = String(now.getUTCMinutes()).padStart(2, '0')
  return `${y}-${mo}-${d} ${h}:${mi} UTC`
}
